### ISSUE TITLE
Can't delete users from list

### ISSUE THREAD

**Issue by 4doom4** [charlesthk/python-mailchimp#113]
Hi,
i get None in return when executing client.lists.members.delete(MAILCHIMP_LIST_ID, subscriber_hash). At the same time I can update are create members in this list without any problem. Was there a recent change in API?
Thanks,
Max

**Comment by stephenross** [comment]
Please take a look at the README if you have recently updated the mailchimp3 plugin as version 2.x is vastly different from 1.x. In general, most delete commands in the MailChimp API return an HTTP 204 (No Content) header, with the expectedly blank body. The List Member commands can be found [here](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/), with the delete performing this way. For any delete command that receives a 204 status code, we do not return anything, otherwise you will receive a JSON object of the data provided in the return.

Please let us know if there are any further questions about this or if this didn't answer your question.
