### ISSUE TITLE
urllib3 problem

### ISSUE THREAD

**Issue by jersobh** [charlesthk/python-mailchimp#169]
Hi there,

I'm getting this error while I try to get the lists:

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='<my-secretkey>.api.mailchimp.com', port=443): Max retries exceeded with url: /3.0/lists?offset=0&count=1000&fields=lists.name%2Clists.id%2Ctotal_items (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f538a44e940>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by stephenross** [comment]
Looking at the error, you did not provide proper authentication as the host is incomplete. All MailChimp API calls hit one of the datacenters in a format of `DATACENTER.api.mailchimp.com`, and your host is just `.api.mailchimp.com`. What values did you provide when you initialized the MailChimpClient?

**Comment by jersobh** [comment]
yep, it was a typo error, sorry about that

**Comment by maheshbist111** [comment]
Hi there,
I'm getting this error while I try to get the lists:

ConnectionError at /admin/marketing/marketingpreference/add/
HTTPSConnectionPool(host='none.api.mailchimp.com', port=443): Max retries exceeded with url: /3.0/lists/None/members//28dabb32160f82570906312f23ae4c18 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x050E7A30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

and I have this config

class Mailchimp(object):
    def __init__(self):
        super(Mailchimp, self).__init__()
        self.key = MAILCHIMP_API_KEY
        self.api_url = "https://dc.api.mailchimp.com/3.0/".format(
                dc=MAILCHIMP_DATA_CENTER
                )
        self.list_id = MAILCHIMP_EMAIL_LIST_ID
        self.list_endpoint = '{api_url}/lists/{list_id}'.format(
                        api_url = self.api_url,
                        list_id=self.list_id
                    )
