### ISSUE TITLE
"Add or update a list member" doesn't compute hash

### ISSUE THREAD

**Issue by aaugustin** [charlesthk/python-mailchimp#48]
#24 added `member.create_or_update`, however, it expects the subscriber hash in argument instead of computing it from the email address.

This surprised me because I expected the library to deal with that sort of low level concerns.

There's a `mailchimp3.helpers.get_subscriber_hash` function to compute this hash but it doesn't appear to be called anywhere. It was added in 344398b79f92268de88689ab15cda2c3cef918e7.

It's unclear to me whether it's a design decision or an oversight to have users perform hashing themselves. Perhaps someone who knows the history of this library could help?

Three courses of actions are possible at this point:

- document that `member_id` can be computed with `get_subscriber_hash`
- document that `member_id` is an email address and compute the hash automatically
- accept both an email address and a hash; if it looks like a hash i.e. it matches `$[0-9a-f]{16}$`, use it as is; if it contains an `@` assume it's an email and hash it; if it's something else raise an exception.

I'm happy to provide a patch for either of these options.

**Comment by stephenross** [comment]
I have added this to my branch that is currently sitting in PR #45. Please take a look and let me know if that is what you had in mind, it is commit [26f100d](https://github.com/charlesthk/python-mailchimp/pull/45/commits/26f100dd2b46703bd3f74e36090f84117e9ed39a)

**Comment by charlesthk** [comment]
When you get all members in a list, mailchimp gives you the id (=the hash) for each member.

Based on that, I suggest we replace `member_id` kwargs with `member_id_or_email`, then we : 
1 - check if the value is an email of an hash, otherwise we return an exception
2 - if it is a hash, continue
3 - if it is an email, compute the hash and continue

This way, we can stick to mailchimp API's structure an give any user the flexibility to use an id (hash) or an email.

What do you guys think about that ?

**Comment by aaugustin** [comment]
@stephenross There's a lot of changes in #45; I think it might be easier to fix this separately.

**Comment by stephenross** [comment]
Take a look at the [helpers.py](https://github.com/stephenross/python-mailchimp/blob/bc8a6e255d8e8bf2872fb28dbcb0619ea8f9f318/mailchimp3/helpers.py) file that I have updated. The plan will be to pass anything that should be a subscriber_hash to the `check_subscriber_hash()` function, which will return the value if it is a 32 character hex string (that MD5 generates), and if there is no match, it will attempt to convert it to a hash using `get_subscriber_hash()`. That function will run the string through a regex check to verify that it is a valid email address (no idea on what 0.1% that regex doesn't cover, but I am willing to bet it will be someone that has an awkward email address on purpose and not one that will actually be used). If the regex says the email is a valid address, we compute the MD5 hash and return that, since that is what the API will be expecting. Anywhere where the API expects an email address will use just the regex checking function (`check_subscriber_email()`)

This follows what @charlesthk said, just with a slight reorder:
1. If the value is a valid hash, assume it is correct and return it
2. If the value is not a valid hash, check to see if it is a valid email
3. If no, raise a ValueError, if yes, compute and return the hash

We obviously must trust any hash sent to us that fits the proper MD5 output since we can't verify that an email address was used to compute the hash, but this should resolve any issues where people are trying to throw email addresses at the endpoints that expect hashes, which we can account for using these.

**Comment by stephenross** [comment]
With the merging of PR #45 all of the methods that act on list members by using a provided hash will now verify whether the item passed was a hash or an email address, and if the latter, compute the former. The only time an error will be returned now will be if the user passes something that is neither a hash nor an email address, otherwise an attempt will be made to send the request.
