### ISSUE TITLE
If the subscriber exists

### ISSUE THREAD

**Issue by raagin** [charlesthk/python-mailchimp#57]
If the subscriber exists, and i use: member.create method. It is return to me HTTPError which have no explanation.

**Comment by stephenross** [comment]
Please ensure you are using the most recent version of the python-mailchimp (mailchimp3 on PyPi, version 2.0.0). The new version does not use the singular syntax that the older version did, so you would be looking at something like `client.members.create()`. Please past a copy of the error message that you received as well so that we can take a look if you are able to confirm that you are using python-mailchimp 2.0.0.

**Comment by charlesthk** [comment]
@stephenross maybe we could consider put singular name in addition to plurals for backward compatibility ?

**Comment by stephenross** [comment]
@charlesthk I thought about that as well, probably would be a good idea with a deprecation notice if they are used, to make the 2.0.0 transition less destructive. I am not quite sure how to do something like a deprecation notice though, so if you have any suggestions I would be happy to take a look at merging the old structure with the new.

**Comment by raagin** [comment]
Yes, you are right! by default "pip install mailchimp3" sent me mailchimp3-1.0.26 version.
Thank you!
