### ISSUE TITLE
Schedule Campaign TimeZone Issue

### ISSUE THREAD

**Issue by YuanZheCSYZ** [charlesthk/python-mailchimp#85]
In file _entities/campaignactions.py_ line 97, it seems the the method **utcoffset** takes one argument.
`if data['schedule_time'].tzinfo.utcoffset() != timedelta(0):`

In my case I convert the local datetime to utc as below, is this the right way to do it?
`datetime.utcfromtimestamp(local_time.timestamp()).replace(tzinfo=datetime.timezone.utc)`

Thanks!

**Comment by stephenross** [comment]
The `utcoffset()` method as used in the code is a `datetime.tzinfo.utcoffset()`, which only requires a `self` argument and will return either `None` or a `timedelta` object with a value of how far the current timestamp is from UTC (with 0 meaning they are the same). We check this value instead of attempting to alter the timezone to match UTC because of the difficulties in the various implementations of timezones. Take a look at the docs [here](https://docs.python.org/2/library/datetime.html#datetime.datetime.utcoffset) for the specific usage that we are using.

**Comment by stephenross** [comment]
Just noticed that you are asking on conversion of your local time to the UTC that mailchimp requires. Looking at that, it looks good per the documentation on those parts of `datetime`. You can always do some testing by attempting to send the data and see what the interface tells you (MailChimp allows API access even for free users, so just make a new free account if you don't want to worry about messing with production data or list sending). I believe that you should be able to see when in your local time a campaign is scheduled for within the normal MailChimp interface.

**Comment by YuanZheCSYZ** [comment]
I see what's wrong. The utcoffset method of datetime.time object does not require any argument while that of datetime.datetime is needed

**Comment by vinicius-ronconi** [comment]
Hi! I'm facing the same problem here, but I don't know how to fix it.

The only way I was able to do that was replacing [this comparison](https://github.com/charlesthk/python-mailchimp/blob/master/mailchimp3/entities/campaignactions.py#L97) with:
`if data['schedule_time'].tzinfo.utcoffset() != timedelta(0):`

the data['schedule_time'] was created like this:
`my_unaware_dt.replace(tzinfo=pytz.timezone('UTC'))`

What am I doing wrong here?
